version: "3.8"

services:
  neovim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gotty
    ports:
      - "8080:8080"
    volumes:
      - ~/src:/root/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
