version: "3.8"

services:
  neovim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttyd
    ports:
      - "8080:8080"
      - "23:22"
      - "7681:7681"
    volumes:
      - ~/src:/root/src
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh:/root/.ssh
    restart: always
